// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
//        maven { url 'http://maven.aliyun.com/nexus/content/groups/public' }
//        jcenter()
//        google()

        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://maven.aliyun.com/repository/google'}
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin'}
        maven { url 'https://maven.aliyun.com/repository/public'}
        google() // Android Studio 3.0开始需要添加这行
        mavenCentral()
    }
    dependencies {
        //classpath 'com.android.tools.build:gradle:3.6.3'
        //classpath 'com.github.dcendents:android-maven-gradle-plugin:1.5'
        classpath 'com.android.tools.build:gradle:4.2.2'
        //classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
//        maven { url 'http://maven.aliyun.com/nexus/content/groups/public' }
//        jcenter()
//        maven { url "https://jitpack.io" }
//        google()

        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://maven.aliyun.com/repository/google'}
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin'}
        maven { url 'https://maven.aliyun.com/repository/public'}
        google() // Android Studio 3.0开始需要添加这行
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
